# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-19 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personsManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='created_by',
            new_name='added_by',
        ),
    ]
